### PR TITLE
Update blocklist.txt

### PR DESCRIPTION
**Pull request by Morty-Feldman**

### CODE REVIEW

**Comment by cunnie** [comment]
Hey @Morty-Feldman 

I love this! Could you do me one favor: change the commit message from _what_ you did "Update blocklist.txt" (which is self-evident from reviewing the commit) to _why_ you did the commit. For example:

> Prevent unfair mirroring of n4g.com
>
> 128.140.77.135 is mirroring N4G.com, a gaming news aggregator, and stealing ad revenue.

Once you change the commit message, do a force-push so there's only one commit message.

**Comment by Morty-Feldman** [comment]
Okay - no IPs are currently mirroring N4G as far as I'm aware (I had Hetzner take those machines down over the past couple of months).

But I was thinking of blocking all of the obvious mirrors that you can find here - https://www.google.com/search?q=site%3Asslip.io

Is that something that I should do to prevent this sort of abuse of your service or would you rather go through those and block them?

**Comment by cunnie** [comment]
Hi @Morty-Feldman 

> But I was thinking of blocking all of the obvious mirrors that you can find here - https://www.google.com/search?q=site%3Asslip.io

> Is that something that I should do to prevent this sort of abuse of your service or would you rather go through those and block them?

As worthy of an effort that would be, I do not have the time to swat down fake sites. I'm willing to review PRs to block them, but that's as far as my effort extends.

Remember: not all mirrors are illegitimate: the classic example is a designer throwing together a website and providing a link to their customer ("click this link to see my design!"). We don't want to punish innocent users.

Also, the volume of websites to review is simply astounding: my nameservers answer 200 queries _per second_; if we limit our focus to websites that have acquired Let's Encrypt TLS certificates, that narrows the search down to 3,000 websites (I've recently submitted a request to bump our limit to 5,000).

Also, the shutdowns are largely ineffective: the miscreant merely switches to a different IP address: voila — no more block.



I also suspect that your

**Comment by cunnie** [comment]
Let me know when you've re-written the commit message and done a force-push.

**Comment by Morty-Feldman** [comment]
Hey, @cunnie - I just had an idea.

Would it be possible to setup sslip.io to send the http header `X-Robots-Tag: noindex` whenever it serves a page?

That way, abusers would stop using your service to flood search engines with mirrored websites AND people can still use your service for what it was intended for.

A bonus is that you would use a lot fewer resources because this would stop the hundreds of abusers that are currently using your service for this purpose.

**Comment by cunnie** [comment]
> Would it be possible to setup sslip.io to send the http header X-Robots-Tag: noindex whenever it serves a page?

Nice idea, not possible. My servers only return DNS queries, not HTTP. No HTTP → no headers.

**Comment by Morty-Feldman** [comment]
> > Would it be possible to setup sslip.io to send the http header X-Robots-Tag: noindex whenever it serves a page?
> 
> Nice idea, not possible. My servers only return DNS queries, not HTTP. No HTTP → no headers.

Ah, I see. Would it be possible to do so via robots.txt that you can have available at `https://sslip.io/robots.txt` ?

**Comment by cunnie** [comment]
> Ah, I see. Would it be possible to do so via robots.txt that you can have available at https://sslip.io/robots.txt ?

That's not possible according to ChatGPT:

- The robots.txt file is generally considered to be effective only for the specific host, protocol, and port number where it is located. This means that a robots.txt file located at http://sslip.io/robots.txt will only provide crawling instructions for URLs that begin with http://sslip.io/.

- Subdomain Independence: Each subdomain is viewed as a separate entity with respect to robots.txt files. Therefore, a robots.txt file placed at http://sslip.io/robots.txt does not automatically apply to http://127.0.0.1.sslip.io or any other subdomain. Each subdomain that requires specific rules for web crawlers must have its own robots.txt file at the root of the subdomain.

**Comment by Morty-Feldman** [comment]
> > Ah, I see. Would it be possible to do so via robots.txt that you can have available at https://sslip.io/robots.txt ?
> 
> That's not possible according to ChatGPT:
> 
>     * The robots.txt file is generally considered to be **effective only for the specific host, protocol, and port number where it is located**. This means that a robots.txt file located at http://sslip.io/robots.txt will only provide crawling instructions for URLs that begin with http://sslip.io/.
> 
>     * Subdomain Independence: Each subdomain is viewed as a separate entity with respect to robots.txt files. Therefore, a robots.txt file placed at http://sslip.io/robots.txt does not automatically apply to http://127.0.0.1.sslip.io or any other subdomain. Each subdomain that requires specific rules for web crawlers must have its own robots.txt file at the root of the subdomain.

I see. Yes, this is a frustrating situation. I can't imagine why there are so many abusers of your service - what do they get out of doing this?

The only other thing I can think of for now is create a Google Search Console account for sslip.io then use the Removals page to wipe out all subdomains - https://search.google.com/search-console/removals

**Comment by cunnie** [comment]
> The only other thing I can think of for now is create a Google Search Console account for sslip.io then use the Removals page to wipe out all subdomains - https://search.google.com/search-console/removals

Too much work; not inclined to do it. Sorry.

**Pull request closed without merging**
